my_module_admin_configure:
    path: /mymodule/configure
    methods: [GET]
    defaults:
        _controller: 'PrestaShop\Module\MyModule\Controller\Admin\MyModuleController::configure'
        _legacy_controller: 'AdminMyModule'