services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  mymodule.data_service:
    class: MyModule\Service\DataService
    # arguments: ['@service_container']

  
imports:
  - {resource: 'commands.yml'}
  - {resource: 'controllers.yml'}

