services:
  rushdi.my_module.my_test_command:
    class: MyModule\Command\MyTestCommand
    tags:
      - { name: 'console.command', command: 'my-module:my-test-command' }

  MyModule\Controller\AdminMyModuleController:
    class: MyModule\Controller\AdminMyModuleController
    arguments: []
    tags:
      - { name: controller.service_arguments }